# Site settings
title: My Test Site
description: >- 
  This is a brief description of my project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kw98ftt.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima # or any other theme you're using

# Other settings
github_username: kw98ftt
